/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'vw-blue': '#002733',
        'vw-cyan': '#00B0F0',
        "tertiary": "#1b0900",
        "on-surface": "#0d1c2d",
        "on-secondary": "#ffffff",
        "surface": "#f8f9ff",
        "primary-fixed": "#c5e8f8",
        "on-error": "#ffffff",
        "tertiary-container": "#3c1a00",
        "on-primary-fixed-variant": "#2a4b58",
        "surface-variant": "#d4e4fa",
        "surface-container-high": "#dbe9ff",
        "secondary-container": "#a1e7ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#8bd1e8",
        "surface-container-highest": "#d4e4fa",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001f27",
        "on-background": "#0d1c2d",
        "surface-tint": "#426370",
        "secondary": "#13677b",
        "on-surface-variant": "#41484b",
        "surface-container-low": "#eef4ff",
        "surface-bright": "#f8f9ff",
        "outline-variant": "#c1c7cb",
        "tertiary-fixed": "#ffdcc6",
        "primary": "#001016",
        "inverse-primary": "#aaccdb",
        "primary-container": "#002733",
        "outline": "#72787b",
        "on-primary-fixed": "#001f29",
        "on-secondary-fixed-variant": "#004e5f",
        "secondary-fixed": "#b2ebff",
        "on-primary": "#ffffff",
        "surface-dim": "#ccdbf2",
        "error": "#ba1a1a",
        "inverse-on-surface": "#e9f1ff",
        "background": "#f8f9ff",
        "tertiary-fixed-dim": "#ffb785",
        "on-secondary-container": "#18697e",
        "surface-container": "#e5efff",
        "on-tertiary-fixed": "#301400",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#aaccdb",
        "on-tertiary-container": "#d56f10",
        "on-primary-container": "#6e8f9e",
        "inverse-surface": "#233143",
        "on-tertiary-fixed-variant": "#713700"
      },
      borderRadius: {
        "panel": "12px"
      },
      spacing: {
        "container-margin": "24px",
        "gutter": "16px",
      },
      fontFamily: {
        "sans": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk"],
        "code-data": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "title-md": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "code-data": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
